# Generated by Django 3.1 on 2020-08-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rubric',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
